"""Reconstruct button_handler in alerts/commands.py to fix corruption and add missing handlers."""

import os

file_path = r"c:\Users\HP USER\Documents\Data Analyst\solana_bot\alerts\commands.py"

with open(file_path, "r", encoding="utf-8") as f:
    lines = f.readlines()

# Find start and end of button_handler
start_idx = -1
end_idx = -1

for i, line in enumerate(lines):
    if "async def button_handler(update: Update" in line:
        start_idx = i
        break

if start_idx != -1:
    # Find the next function definition to determine end of button_handler
    for i in range(start_idx + 1, len(lines)):
        if line.startswith("async def ") or line.startswith("def "):
            end_idx = i
            break
    
    if end_idx == -1:
        end_idx = len(lines)

    # Construct the new button_handler body
    new_handler = [
        'async def button_handler(update: Update, context: ContextTypes.DEFAULT_TYPE, user_manager: UserManager, portfolio_manager=None):\n',
        '    """Handle inline keyboard button callbacks."""\n',
        '    from alerts.trading_buttons import (\n',
        '        handle_pnl_page_callback, handle_portfolio_page_callback,\n',
        '        handle_sell_confirm_callback, handle_sell_execute_callback,\n',
        '        handle_sell_all_confirm_callback, handle_sell_all_execute_callback,\n',
        '        handle_sell_cancel_callback\n',
        '    )\n',
        '    from alerts.menu_handler import handle_menu_callback\n',
        '    \n',
        '    query = update.callback_query\n',
        '    data = query.data\n',
        '    \n',
        '    # --- Handle Menu Navigation Callbacks First ---\n',
        '    if data.startswith("menu_") or data.startswith("mode_") or data.startswith("grade_") or \\\n',
        '       data.startswith("init_capital:") or data.startswith("reset_capital") or data.startswith("custom_capital") or \\\n',
        '       data.startswith("settings_") or data.startswith("alpha_") or data.startswith("setalerts_") or \\\n',
        '       data.startswith("tp_") or data.startswith("predict_") or data.startswith("help_") or \\\n',
        '       data.startswith("myalerts_") or data.startswith("history_") or data.startswith("performance_") or \\\n',
        '       data == "watchlist_direct" or data == "portfolio_direct" or data == "pnl_direct" or \\\n',
        '       data.startswith("resetcapital_") or data == "grades_done" or data.startswith("enable_") or data == "mysettings_direct":\n',
        '        if portfolio_manager:\n',
        '            await handle_menu_callback(update, context, user_manager, portfolio_manager)\n',
        '        return\n',
        '    \n',
        '    # --- Handle Trading Button Callbacks ---\n',
        '    # Handle all buy-related callbacks (amount, TP, SL, custom)\n',
        '    if (data.startswith("buy_amount:") or data.startswith("buy_custom:") or \n',
        '        data.startswith("buy_tp:") or data.startswith("buy_sl:") or\n',
        '        data == "buy_tp_custom" or data == "buy_sl_custom"):\n',
        '        if portfolio_manager:\n',
        '            await buy_token_callback_handler(update, context, user_manager, portfolio_manager)\n',
        '        return\n',
        '    \n',
        '    # Handle message deletion (Cancel button)\n',
        '    if data == "delete_msg":\n',
        '        await query.answer()\n',
        '        await query.message.delete()\n',
        '        return\n',
        '    \n',
        '    # PnL pagination\n',
        '    if data.startswith("pnl_page:"):\n',
        '        if portfolio_manager:\n',
        '            await handle_pnl_page_callback(update, context, user_manager, portfolio_manager)\n',
        '        return\n',
        '    \n',
        '    # Portfolio pagination\n',
        '    elif data.startswith("portfolio_page:"):\n',
        '        if portfolio_manager:\n',
        '            await handle_portfolio_page_callback(update, context, user_manager, portfolio_manager)\n',
        '        return\n',
        '    \n',
        '    # Sell confirmation for single position\n',
        '    elif data.startswith("sell_confirm:"):\n',
        '        if portfolio_manager:\n',
        '            await handle_sell_confirm_callback(update, context, user_manager, portfolio_manager)\n',
        '        return\n',
        '    \n',
        '    # Execute single position sell\n',
        '    elif data.startswith("sell_execute:"):\n',
        '        if portfolio_manager:\n',
        '            await handle_sell_execute_callback(update, context, user_manager, portfolio_manager)\n',
        '        return\n',
        '    \n',
        '    # Sell all confirmation\n',
        '    elif data == "sell_all_confirm":\n',
        '        if portfolio_manager:\n',
        '            await handle_sell_all_confirm_callback(update, context, user_manager, portfolio_manager)\n',
        '        return\n',
        '    \n',
        '    # Execute sell all\n',
        '    elif data == "sell_all_execute":\n',
        '        if portfolio_manager:\n',
        '            await handle_sell_all_execute_callback(update, context, user_manager, portfolio_manager)\n',
        '        return\n',
        '    \n',
        '    # Cancel sell\n',
        '    elif data == "sell_cancel":\n',
        '        await handle_sell_cancel_callback(update, context)\n',
        '        return\n',
        '    \n',
        '    # --- End Trading Button Callbacks ---\n',
        '    \n',
        '    # Acknowledge the click immediately\n',
        '    # For refresh, show a loading text\n',
        '    if data.startswith("refresh_alpha:"):\n',
        '        await query.answer("Refreshing data...")\n',
        '    else:\n',
        '        await query.answer() \n',
        '    \n',
        '    chat_id = str(query.from_user.id)\n',
        '    data = query.data\n',
        '\n',
        '    # --- Handle Alpha Refresh Button ---\n',
        '    if data.startswith("refresh_alpha:"):\n',
        '        try:\n',
        '            mint = data.split(":", 1)[1]\n',
        '            \n',
        '            # Load the initial state using the correctly constructed path\n',
        '            alerts_state = safe_load(ALPHA_ALERTS_STATE_FILE, {})\n',
        '            initial_state = alerts_state.get(mint)\n',
        '            \n',
        '            if not initial_state:\n',
        '                # If not found, it might be because the alert is too old or path issue persisting\n',
        '                await query.edit_message_text(\n',
        '                    "Error: Initial data not found for this token. It may be too old.",\n',
        '                    reply_markup=None\n',
        '                )\n',
        '                return\n',
        '            \n',
        '            # --- Reply vs. Edit Logic ---\n',
        '            is_refresh_message = query.message.text.startswith("🔄 <b>Refresh:")\n',
        '            \n',
        '            if is_refresh_message:\n',
        '                # --- EDIT LOGIC (for subsequent clicks) ---\n',
        '                symbol = initial_state.get("symbol", "N/A")\n',
        '                loading_message = f"""🔄 <b>Refreshing: ${symbol}</b>\n\n<i>Please wait, fetching live data...</i> \n"""\n',
        '                loading_keyboard = InlineKeyboardMarkup([\n',
        '                    [InlineKeyboardButton("Refreshing... ↻", callback_data=f"refresh_alpha:{mint}")]\n',
        '                ])\n',
        '                \n',
        '                try:\n',
        '                    if query.message.text != loading_message:\n',
        '                        await query.edit_message_text(\n',
        '                            text=loading_message,\n',
        '                            parse_mode="HTML",\n',
        '                            reply_markup=loading_keyboard,\n',
        '                            disable_web_page_preview=True\n',
        '                        )\n',
        '                except Exception as e:\n',
        '                    if "message is not modified" in str(e).lower():\n',
        '                        await query.answer("Already refreshing...")\n',
        '                        return \n',
        '                    raise \n',
        '                \n',
        '                message = await format_alpha_refresh(mint, initial_state)\n',
        '                final_keyboard = InlineKeyboardMarkup([\n',
        '                    [InlineKeyboardButton("Refresh ↻", callback_data=f"refresh_alpha:{mint}")]\n',
        '                ])\n',
        '\n',
        '                await query.edit_message_text(\n',
        '                    text=message,\n',
        '                    parse_mode="HTML",\n',
        '                    reply_markup=final_keyboard,\n',
        '                    disable_web_page_preview=True\n',
        '                )\n',
        '            \n',
        '            else:\n',
        '                # --- REPLY LOGIC (for first click on original alert) ---\n',
        '                message = await format_alpha_refresh(mint, initial_state)\n',
        '                final_keyboard = InlineKeyboardMarkup([\n',
        '                    [InlineKeyboardButton("Refresh ↻", callback_data=f"refresh_alpha:{mint}")]\n',
        '                ])\n',
        '                \n',
        '                await query.message.reply_html(\n',
        '                    text=message,\n',
        '                    reply_markup=final_keyboard,\n',
        '                    disable_web_page_preview=True\n',
        '                )\n',
        '                \n',
        '        except Exception as e:\n',
        '            if "message is not modified" in str(e).lower():\n',
        '                await query.answer("Data is already up to date.")\n',
        '            else:\n',
        '                logger.error(f"Failed to refresh alpha alert: {e}")\n',
        '                await query.answer("Error during refresh.", show_alert=True)\n',
        '        return\n',
        '\n',
        '    # --- Handle CA Analysis Button in Groups ---\n',
        '    if data.startswith("analyze_"):\n',
        '        if query.message.chat.type in ["group", "supergroup"]:\n',
        '            try:\n',
        '                mint_address = data.split("_", 1)[1]\n',
        '                await context.bot.send_message(\n',
        '                    chat_id=query.message.chat_id,\n',
        '                    text=f"<code>{mint_address}</code>",\n',
        '                    parse_mode="HTML"\n',
        '                )\n',
        '                return \n',
        '            except Exception as e:\n',
        '                logging.warning(f"Failed to send CA in group: {e}")\n',
        '                try:\n',
        '                    await query.answer("Error sending address.", show_alert=True)\n',
        '                except:\n',
        '                    pass\n',
        '                return \n',
        '        else:\n',
        '            try:\n',
        '                mint_address = data.split("_", 1)[1]\n',
        '                await query.message.reply_text(f"<code>{mint_address}</code>", parse_mode="HTML")\n',
        '            except Exception as e:\n',
        '                logging.warning(f"Failed to send CA in private chat: {e}")\n',
        '            return\n',
        '\n',
        '    # --- Subscription Check (for all other user-specific commands) ---\n',
        '    if not user_manager.is_subscribed(chat_id):\n',
        '        await query.answer("⛔ You are not subscribed.", show_alert=True)\n',
        '        return\n',
        '    \n',
        '    # --- Mode Selection ---\n',
        '    if data == "mode_alerts":\n',
        '        user_manager.set_modes(chat_id, ["alerts"])\n',
        '        await query.edit_message_text("✅ Mode set to <b>🔔 Alerts Only</b>.", parse_mode="HTML")\n',
        '    elif data == "mode_papertrade":\n',
        '        user_manager.set_modes(chat_id, ["papertrade"])\n',
        '        await query.edit_message_text(\n',
        '            "✅ Mode set to <b>📈 Paper Trading Only</b>.\\n\\n"\n',
        '            "Use <code>/papertrade [capital]</code> to set your starting funds.\\n"\n',
        '            "Example: <code>/papertrade 1000</code>", \n',
        '            parse_mode="HTML"\n',
        '        )\n',
        '    elif data == "mode_both":\n',
        '        user_manager.set_modes(chat_id, ["alerts", "papertrade"])\n',
        '        await query.edit_message_text(\n',
        '            "✅ Mode set to <b>🚀 Both Alerts & Paper Trading</b>.\\n\\n"\n',
        '            "You\'ll receive alerts AND auto-trade signals.\\n"\n',
        '            "Use <code>/papertrade [capital]</code> to configure your trading capital.", \n',
        '            parse_mode="HTML"\n',
        '        )\n',
        '\n',
        '    # --- Grade Configuration ---\n',
        '    elif data == "config_grades":\n',
        '        keyboard = [\n',
        '            [InlineKeyboardButton("🔴 CRITICAL", callback_data="preset_critical"),\n',
        '             InlineKeyboardButton("🔥 CRITICAL + HIGH", callback_data="preset_critical_high")],\n',
        '            [InlineKeyboardButton("📊 All Grades", callback_data="preset_all")]\n',
        '        ]\n',
        '        await query.edit_message_text(\n',
        '            "Please select a preset for your <b>alert grades</b> or use <code>/setalerts</code> for a custom list.", \n',
        '            reply_markup=InlineKeyboardMarkup(keyboard), \n',
        '            parse_mode="HTML"\n',
        '        )\n',
        '    elif data == "preset_critical":\n',
        '        user_manager.update_user_prefs(chat_id, {"grades": ["CRITICAL"]})\n',
        '        await query.edit_message_text("✅ Alert grades updated: <b>CRITICAL</b> only.", parse_mode="HTML")\n',
        '    elif data == "preset_critical_high":\n',
        '        user_manager.update_user_prefs(chat_id, {"grades": ["CRITICAL", "HIGH"]})\n',
        '        await query.edit_message_text("✅ Alert grades updated: <b>CRITICAL + HIGH</b>.", parse_mode="HTML")\n',
        '    elif data == "preset_all":\n',
        '        user_manager.update_user_prefs(chat_id, {"grades": ALL_GRADES.copy()})\n',
        '        await query.edit_message_text("✅ Alert grades updated: <b>ALL</b> grades.", parse_mode="HTML")\n'
    ]

    # Replace the corrupted function with the new one
    lines[start_idx:end_idx] = new_handler
    
    with open(file_path, "w", encoding="utf-8") as f:
        f.writelines(lines)
    
    print("Successfully reconstructed button_handler!")
else:
    print("Could not find button_handler in the file.")
